n1 = int(input('Digite um numero : '))
print('-'*12)
print('{} X {} = {}'.format(n1, 1, n1*1))
print('{} X {} = {}'.format(n1, 1, n1*2))
print('{} X {} = {}'.format(n1, 1, n1*3))
print('{} X {} = {}'.format(n1, 1, n1*4))
print('{} X {} = {}'.format(n1, 1, n1*5))
print('{} X {} = {}'.format(n1, 1, n1*6))
print('{} X {} = {}'.format(n1, 1, n1*7))
print('{} X {} = {}'.format(n1, 1, n1*8))
print('{} X {} = {}'.format(n1, 1, n1*9))
print('{} X {} = {}'.format(n1, 1, n1*10))
print('-'*12)